name: flutter_on_windows
description: A new Flutter project.

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.0-69.2.beta <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  sqflite: ^2.0.2
  intl: ^0.17.0
  flutter_staggered_grid_view: ^0.6.1
  get: ^4.6.1
  flutter_secure_storage: ^5.0.2
  sqflite_common: ^2.2.0
  sqflite_common_ffi: ^2.1.0+2
  hive: ^2.0.6
  hive_flutter: ^1.1.0
  path_provider: ^2.0.9

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^1.0.0
  hive_generator:
  build_runner:

flutter:
  uses-material-design: true

  assets:
    - assets/